# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

let A0 = 456
let A1 = 789
let A2 = 576
let A3 = 4352
let A4 = 8695
let A5 = 9067
let A6 = 34657
let A7 = 985678
let A8 = @sum(A0:A7)
goto A11 A0
